server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/prod_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
custom:
  fileDirPath: /usr/file